apiVersion: v1
kind: ServiceAccount
metadata:
  name: by-meta-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: by-meta-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: by-meta-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: by-meta-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: by-meta-scheduler
      containers:
      - image: paulsbruce/kube-scheduler-by-meta
        name: by-meta-scheduler
        imagePullPolicy: Always
